name: deploy gh-pages

on:
  push: # trigger on pushes to main branch
    branches:
      - "main"
      
  workflow_dispatch: # allow manual trigger from Actions tab
  
permissions:
  contents: read       # read repo files
  pages:    write      # allow deployment to GitHub Pages
  id-token: write      # needed internally by GitHub

concurrency:
  group: "pages"
  cancel-in-progress: false   # dont cancel ongoing deployments

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # setup
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # upload
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./checking

      # deploy to gh-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
